// ABIs for the deployed v4 contracts.

export const TREASURY_ABI = [
  { type: 'constructor', inputs: [{ name: 'usdc', type: 'address', internalType: 'address' }], stateMutability: 'nonpayable' },
  { type: 'function', name: 'USDC', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'address', internalType: 'address' }] },
  { type: 'function', name: 'owner', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'address', internalType: 'address' }] },
  { type: 'function', name: 'authorizedGames', stateMutability: 'view', inputs: [{ name: '', type: 'address', internalType: 'address' }], outputs: [{ name: '', type: 'bool', internalType: 'bool' }] },
  { type: 'function', name: 'balances', stateMutability: 'view', inputs: [{ name: '', type: 'address', internalType: 'address' }, { name: '', type: 'address', internalType: 'address' }], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'rewardPool', stateMutability: 'view', inputs: [{ name: '', type: 'address', internalType: 'address' }], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'protocolFees', stateMutability: 'view', inputs: [{ name: '', type: 'address', internalType: 'address' }], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'totalTokenDistributed', stateMutability: 'view', inputs: [{ name: 'token', type: 'address', internalType: 'address' }], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'feePercent', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'setAuthorizedGame', stateMutability: 'nonpayable', inputs: [{ name: 'game', type: 'address', internalType: 'address' }, { name: 'status', type: 'bool', internalType: 'bool' }], outputs: [] },
  { type: 'function', name: 'setFeePercent', stateMutability: 'nonpayable', inputs: [{ name: 'percent', type: 'uint256', internalType: 'uint256' }], outputs: [] },
  { type: 'function', name: 'withdrawProtocolFees', stateMutability: 'nonpayable', inputs: [{ name: 'token', type: 'address', internalType: 'address' }, { name: 'amount', type: 'uint256', internalType: 'uint256' }], outputs: [] },
  { type: 'function', name: 'withdraw', stateMutability: 'nonpayable', inputs: [{ name: 'token', type: 'address', internalType: 'address' }, { name: 'amount', type: 'uint256', internalType: 'uint256' }], outputs: [] },
  { type: 'function', name: 'chargeFromBalance', stateMutability: 'nonpayable', inputs: [{ name: 'player', type: 'address', internalType: 'address' }, { name: 'token', type: 'address', internalType: 'address' }, { name: 'amount', type: 'uint256', internalType: 'uint256' }], outputs: [] },
  { type: 'function', name: 'chargeDirectUSDC', stateMutability: 'nonpayable', inputs: [{ name: 'player', type: 'address', internalType: 'address' }, { name: 'amount', type: 'uint256', internalType: 'uint256' }], outputs: [] },
  { type: 'function', name: 'depositUSDC', stateMutability: 'nonpayable', inputs: [{ name: 'amount', type: 'uint256', internalType: 'uint256' }], outputs: [] },
  { type: 'function', name: 'rewardPlayer', stateMutability: 'nonpayable', inputs: [{ name: 'player', type: 'address', internalType: 'address' }, { name: 'token', type: 'address', internalType: 'address' }, { name: 'amount', type: 'uint256', internalType: 'uint256' }], outputs: [] },
  { type: 'function', name: 'fundRewardPool', stateMutability: 'nonpayable', inputs: [{ name: 'amount', type: 'uint256', internalType: 'uint256' }], outputs: [] },
  { type: 'function', name: 'rescueToken', stateMutability: 'nonpayable', inputs: [{ name: 'token', type: 'address', internalType: 'address' }, { name: 'to', type: 'address', internalType: 'address' }, { name: 'amount', type: 'uint256', internalType: 'uint256' }], outputs: [] },
  { type: 'function', name: 'rescueETH', stateMutability: 'nonpayable', inputs: [{ name: 'to', type: 'address', internalType: 'address' }, { name: 'amount', type: 'uint256', internalType: 'uint256' }], outputs: [] },
  { type: 'function', name: 'pause', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'unpause', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'transferOwnership', stateMutability: 'nonpayable', inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }], outputs: [] },
  { type: 'function', name: 'renounceOwnership', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'getAllPendingRewards', stateMutability: 'view', inputs: [{ name: 'player', type: 'address', internalType: 'address' }], outputs: [{ name: 'tokens', type: 'address[]', internalType: 'address[]' }, { name: 'amounts', type: 'uint256[]', internalType: 'uint256[]' }] },
  { type: 'function', name: 'getPendingRewards', stateMutability: 'view', inputs: [{ name: 'player', type: 'address', internalType: 'address' }, { name: 'token', type: 'address', internalType: 'address' }], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'getSupportedTokens', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'address[]', internalType: 'address[]' }] },
  { type: 'function', name: 'treasuryBalanceETH', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'treasuryBalanceToken', stateMutability: 'view', inputs: [{ name: 'token', type: 'address', internalType: 'address' }], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'totalETHCollected', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'claimAllTokens', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'claimToken', stateMutability: 'nonpayable', inputs: [{ name: 'token', type: 'address', internalType: 'address' }], outputs: [] },
] as const

export const MATCH3_GAME_ABI = [
  { type: 'constructor', inputs: [{ name: '_treasury', type: 'address', internalType: 'address' }, { name: '_signer', type: 'address', internalType: 'address' }], stateMutability: 'nonpayable' },
  { type: 'function', name: 'treasury', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'address', internalType: 'contract ITreasury' }] },
  { type: 'function', name: 'signer', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'address', internalType: 'address' }] },
  { type: 'function', name: 'owner', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'address', internalType: 'address' }] },
  { type: 'function', name: 'playFee', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'continueFee', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'maxReward', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'maxContinues', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint8', internalType: 'uint8' }] },
  { type: 'function', name: 'sessionDuration', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'nextSessionId', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'sessions', stateMutability: 'view', inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }], outputs: [
    { name: 'player', type: 'address', internalType: 'address' },
    { name: 'token', type: 'address', internalType: 'address' },
    { name: 'startTime', type: 'uint64', internalType: 'uint64' },
    { name: 'completed', type: 'bool', internalType: 'bool' },
  ] },
  { type: 'function', name: 'continuesUsed', stateMutability: 'view', inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }], outputs: [{ name: '', type: 'uint256', internalType: 'uint8' }] },
  { type: 'function', name: 'usedMessages', stateMutability: 'view', inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }], outputs: [{ name: '', type: 'bool', internalType: 'bool' }] },
  { type: 'function', name: 'startGame', stateMutability: 'payable', inputs: [{ name: 'token', type: 'address', internalType: 'address' }, { name: 'useDeposit', type: 'bool', internalType: 'bool' }], outputs: [{ name: 'sessionId', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'continueLevel', stateMutability: 'payable', inputs: [{ name: 'sessionId', type: 'uint256', internalType: 'uint256' }, { name: 'useDeposit', type: 'bool', internalType: 'bool' }], outputs: [] },
  { type: 'function', name: 'completeLevel', stateMutability: 'nonpayable', inputs: [{ name: 'sessionId', type: 'uint256', internalType: 'uint256' }, { name: 'reward', type: 'uint256', internalType: 'uint256' }, { name: 'signature', type: 'bytes', internalType: 'bytes' }], outputs: [] },
  { type: 'function', name: 'setSigner', stateMutability: 'nonpayable', inputs: [{ name: '_signer', type: 'address', internalType: 'address' }], outputs: [] },
  { type: 'function', name: 'setMaxReward', stateMutability: 'nonpayable', inputs: [{ name: '_max', type: 'uint256', internalType: 'uint256' }], outputs: [] },
  { type: 'function', name: 'setContinueFee', stateMutability: 'nonpayable', inputs: [{ name: '_fee', type: 'uint256', internalType: 'uint256' }], outputs: [] },
  { type: 'function', name: 'setSessionConfig', stateMutability: 'nonpayable', inputs: [{ name: '_maxContinues', type: 'uint8', internalType: 'uint8' }, { name: '_sessionDuration', type: 'uint256', internalType: 'uint256' }], outputs: [] },
  { type: 'function', name: 'setBoosterPrices', stateMutability: 'nonpayable', inputs: [{ name: '_hammer', type: 'uint256', internalType: 'uint256' }, { name: '_shuffle', type: 'uint256', internalType: 'uint256' }, { name: '_colorBomb', type: 'uint256', internalType: 'uint256' }, { name: '_hammerPack', type: 'uint256', internalType: 'uint256' }, { name: '_shufflePack', type: 'uint256', internalType: 'uint256' }, { name: '_colorBombPack', type: 'uint256', internalType: 'uint256' }], outputs: [] },
  { type: 'function', name: 'pause', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'unpause', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'transferOwnership', stateMutability: 'nonpayable', inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }], outputs: [] },
  { type: 'function', name: 'renounceOwnership', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'setPlayFee', stateMutability: 'nonpayable', inputs: [{ name: '_fee', type: 'uint256', internalType: 'uint256' }], outputs: [] },
  { type: 'function', name: 'setTreasury', stateMutability: 'nonpayable', inputs: [{ name: '_treasury', type: 'address', internalType: 'address' }], outputs: [] },
  { type: 'function', name: 'hammerPrice', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'shufflePrice', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'colorBombPrice', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'hammerPackPrice', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'shufflePackPrice', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'colorBombPackPrice', stateMutability: 'view', inputs: [], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'getBoosterPrice', stateMutability: 'view', inputs: [{ name: 'boosterType', type: 'uint8', internalType: 'uint8' }, { name: 'isPack', type: 'bool', internalType: 'bool' }], outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }] },
  { type: 'function', name: 'buyBooster', stateMutability: 'payable', inputs: [{ name: 'boosterType', type: 'uint8', internalType: 'uint8' }, { name: 'isPack', type: 'bool', internalType: 'bool' }, { name: 'token', type: 'address', internalType: 'address' }, { name: 'useDeposit', type: 'bool', internalType: 'bool' }], outputs: [] },
] as const
