import nodemailer from 'nodemailer'

export interface EmailConfig {
  host: string
  port: number
  secure: boolean
  user: string
  pass: string
  from: string
}

export interface SecurityAlert {
  type: string
  severity: string
  ip: string
  details: string
  timestamp: string
  threatCount: number
}

class EmailService {
  private transporter: nodemailer.Transporter | null = null
  private config: EmailConfig | null = null

  configure(config: EmailConfig) {
    this.config = config
    this.transporter = nodemailer.createTransport({
      host: config.host,
      port: config.port,
      secure: config.secure,
      auth: {
        user: config.user,
        pass: config.pass,
      },
    })
  }

  async sendSecurityAlert(
    recipient: string,
    alert: SecurityAlert
  ): Promise<boolean> {
    if (!this.transporter || !this.config) {
      console.error('Email service not configured')
      return false
    }

    const subject = `🚨 SECURITY ALERT: ${alert.type.toUpperCase()} - ${alert.severity.toUpperCase()}`

    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>Security Alert - Joybit</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
            .container { max-width: 600px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 8px 8px 0 0; margin: -30px -30px 20px -30px; }
            .alert-badge { display: inline-block; padding: 5px 15px; border-radius: 20px; font-size: 12px; font-weight: bold; text-transform: uppercase; }
            .severity-high { background: #dc3545; color: white; }
            .severity-medium { background: #fd7e14; color: white; }
            .severity-low { background: #ffc107; color: black; }
            .details { background: #f8f9fa; padding: 15px; border-radius: 5px; margin: 15px 0; border-left: 4px solid #667eea; }
            .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; color: #666; font-size: 12px; }
            .action-button { display: inline-block; background: #667eea; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; margin: 10px 0; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>🛡️ Security Alert</h1>
              <p>Joybit Security Monitoring System</p>
            </div>

            <div class="alert-badge severity-${alert.severity.toLowerCase()}">
              ${alert.severity} Priority
            </div>

            <h2>Threat Detected</h2>
            <div class="details">
              <strong>Type:</strong> ${alert.type}<br>
              <strong>IP Address:</strong> ${alert.ip}<br>
              <strong>Time:</strong> ${new Date(alert.timestamp).toLocaleString()}<br>
              <strong>Active Threats:</strong> ${alert.threatCount}<br>
              <strong>Details:</strong> ${alert.details}
            </div>

            <p><strong>Recommended Actions:</strong></p>
            <ul>
              <li>Review the security dashboard for more details</li>
              <li>Check recent logs for similar patterns</li>
              <li>Consider blocking the IP if necessary</li>
              <li>Monitor for additional threats from this source</li>
            </ul>

            <a href="${process.env.NEXT_PUBLIC_APP_URL || 'https://joybit.vercel.app'}/admin" class="action-button">
              🔍 View Security Dashboard
            </a>

            <div class="footer">
              <p>This alert was generated by Joybit's automated security monitoring system.</p>
              <p>If you believe this is a false positive, please review your security settings.</p>
              <p>© 2025 Joybit - Decentralized Gaming Platform</p>
            </div>
          </div>
        </body>
      </html>
    `

    const text = `
SECURITY ALERT - Joybit Platform

Threat Type: ${alert.type}
Severity: ${alert.severity}
IP Address: ${alert.ip}
Time: ${new Date(alert.timestamp).toLocaleString()}
Active Threats: ${alert.threatCount}

Details: ${alert.details}

Please check the security dashboard immediately:
${process.env.NEXT_PUBLIC_APP_URL || 'https://joybit.vercel.app'}/admin

This is an automated message from Joybit Security Monitoring.
    `.trim()

    try {
      await this.transporter.sendMail({
        from: `"Joybit Security" <${this.config.from}>`,
        to: recipient,
        subject,
        text,
        html,
      })

      console.log(`Security alert email sent to ${recipient}`)
      return true
    } catch (error) {
      console.error('Failed to send security alert email:', error)
      return false
    }
  }

  async sendTestEmail(recipient: string): Promise<boolean> {
    if (!this.transporter || !this.config) {
      console.error('Email service not configured')
      return false
    }

    const subject = '🧪 Test Email - Joybit Security System'
    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2>🧪 Joybit Security Email Test</h2>
        <p>This is a test email to verify your email notification settings.</p>
        <p>If you received this email, your security notifications are properly configured!</p>
        <p><strong>Time:</strong> ${new Date().toLocaleString()}</p>
        <hr>
        <p><small>This is an automated test message from Joybit Security System.</small></p>
      </div>
    `

    try {
      await this.transporter.sendMail({
        from: `"Joybit Security" <${this.config.from}>`,
        to: recipient,
        subject,
        html,
      })

      console.log(`Test email sent to ${recipient}`)
      return true
    } catch (error) {
      console.error('Failed to send test email:', error)
      return false
    }
  }

  isConfigured(): boolean {
    return this.transporter !== null && this.config !== null
  }
}

export const emailService = new EmailService()